### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ShineiIchijo** [soruly/trace.moe-api#66]
Genres and gif format file for every results.

**Comment by soruly** [comment]
All anime info from the `anilist` field, like genres are from Anilist. I'll only provide a minimal set of data from Anilist because there are just too many different fields users may / may not need. It'd be tedious for me to proxy anilist queries through trace.moe to anilist. What you can do is to get only the anilist ID, and the make another request to Anilist API to gather whatever information want. See https://anilist.gitbook.io/anilist-apiv2-docs/

For video preview file format, I'd not provide GIF format because it's too inefficient and is a waste of traffic. You'll need to download the mp4 and convert to GIF yourself. Note, you can use the `&mute` param to get a silent mp4 without audio track. Some systems, like Telegram, may treat silent mp4 files as GIF.
